In [3]:
#data cleaning
import pandas as pd
Data=pd.read_csv("car_prices.csv")
print("Initial Dataset Preview:\n",Data.head())

Initial Dataset Preview:
    year   make                model        trim   body transmission  \
0  2015    Kia              Sorento          LX    SUV    automatic
1  2015    Kia              Sorento          LX    SUV    automatic
2  2014    BMW             3 Series  328i SULEV  Sedan    automatic
3  2015  Volvo                  S60          T5  Sedan    automatic
4  2014    BMW  6 Series Gran Coupe        650i  Sedan    automatic

                 vin state  condition  odometer  color interior  \
0  5xyktca69fg566472    ca        5.0   16639.0  white    black
1  5xyktca69fg561319    ca        5.0    9393.0  white    beige
2  wba3c1c51ek116351    ca       45.0    1331.0   gray    black
3  yv1612tb4f1310987    ca       41.0   14282.0  white    black
4  wba6b2c57ed129731    ca       43.0    2641.0   gray    black

                                   seller      mmr  sellingprice  \
0                 kia motors america  inc  20500.0       21500.0
1                 kia motors america  inc  20800.0       21500.0
2  financial services remarketing (lease)  31900.0       30000.0
3                 volvo na rep/world omni  27500.0       27750.0
4  financial services remarketing (lease)  66000.0       67000.0

                                  saledate
0  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2  Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3  Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4  Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

In [4]:
# Step 3: Check for missing values
print("\nMissing Values in Each Column:\n")
Data.isnull().sum()

Missing Values in Each Column:

year                0
make            10301
model           10399
trim            10651
body            13195
transmission    65352
vin                 4
state               0
condition       11820
odometer           94
color             749
interior          749
seller              0
mmr                38
sellingprice       12
saledate           12
dtype: int64

In [13]:
# Step 4: Drop missing values (optional, or use fillna())
Data.dropna() 
Data.fillna("unknown")

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558831,2011,BMW,5 Series,528i,Sedan,automatic,wbafr1c53bc744672,fl,39.0,66403.0,white,brown,lauderdale imports ltd bmw pembrok pines,20300.0,22800.0,Tue Jul 07 2015 06:15:00 GMT-0700 (PDT)
558833,2012,Ram,2500,Power Wagon,Crew Cab,automatic,3c6td5et6cg112407,wa,5.0,54393.0,white,black,i -5 uhlmann rv,30200.0,30800.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558834,2012,BMW,X5,xDrive35d,SUV,automatic,5uxzw0c58cl668465,ca,48.0,50561.0,black,black,financial services remarketing (lease),29800.0,34000.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558835,2015,Nissan,Altima,2.5 S,sedan,automatic,1n4al3ap0fc216050,ga,38.0,16658.0,white,black,enterprise vehicle exchange / tra / rental / t...,15100.0,11100.0,Thu Jul 09 2015 06:45:00 GMT-0700 (PDT)
558836,2014,Ford,F-150,XLT,SuperCrew,automatic,1ftfw1et2eke87277,ca,34.0,15008.0,gray,gray,ford motor credit company llc pd,29600.0,26700.0,Thu May 28 2015 05:30:00 GMT-0700 (PDT)

In [16]:
# Step 5: Remove duplicate rows
Data= Data.drop_duplicates()
print(Data)

        year    make                model         trim       body  \
0       2015     Kia              Sorento           LX        SUV
1       2015     Kia              Sorento           LX        SUV
2       2014     BMW             3 Series   328i SULEV      Sedan
3       2015   Volvo                  S60           T5      Sedan
4       2014     BMW  6 Series Gran Coupe         650i      Sedan
...      ...     ...                  ...          ...        ...
558831  2011     BMW             5 Series         528i      Sedan
558833  2012     Ram                 2500  Power Wagon   Crew Cab
558834  2012     BMW                   X5    xDrive35d        SUV
558835  2015  Nissan               Altima        2.5 S      sedan
558836  2014    Ford                F-150          XLT  SuperCrew

       transmission                vin state  condition  odometer  color  \
0         automatic  5xyktca69fg566472    ca        5.0   16639.0  white
1         automatic  5xyktca69fg561319    ca        5.0    9393.0  white
2         automatic  wba3c1c51ek116351    ca       45.0    1331.0   gray
3         automatic  yv1612tb4f1310987    ca       41.0   14282.0  white
4         automatic  wba6b2c57ed129731    ca       43.0    2641.0   gray
...             ...                ...   ...        ...       ...    ...
558831    automatic  wbafr1c53bc744672    fl       39.0   66403.0  white
558833    automatic  3c6td5et6cg112407    wa        5.0   54393.0  white
558834    automatic  5uxzw0c58cl668465    ca       48.0   50561.0  black
558835    automatic  1n4al3ap0fc216050    ga       38.0   16658.0  white
558836    automatic  1ftfw1et2eke87277    ca       34.0   15008.0   gray

       interior                                             seller      mmr  \
0         black                            kia motors america  inc  20500.0
1         beige                            kia motors america  inc  20800.0
2         black             financial services remarketing (lease)  31900.0
3         black                            volvo na rep/world omni  27500.0
4         black             financial services remarketing (lease)  66000.0
...         ...                                                ...      ...
558831    brown           lauderdale imports ltd bmw pembrok pines  20300.0
558833    black                                    i -5 uhlmann rv  30200.0
558834    black             financial services remarketing (lease)  29800.0
558835    black  enterprise vehicle exchange / tra / rental / t...  15100.0
558836     gray                   ford motor credit company llc pd  29600.0

        sellingprice                                 saledate
0            21500.0  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1            21500.0  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2            30000.0  Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3            27750.0  Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4            67000.0  Thu Dec 18 2014 12:30:00 GMT-0800 (PST)
...              ...                                      ...
558831       22800.0  Tue Jul 07 2015 06:15:00 GMT-0700 (PDT)
558833       30800.0  Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558834       34000.0  Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558835       11100.0  Thu Jul 09 2015 06:45:00 GMT-0700 (PDT)
558836       26700.0  Thu May 28 2015 05:30:00 GMT-0700 (PDT)

[472325 rows x 16 columns]

In [21]:
# Step 6: Clean column names 
Data.columns = Data.columns.str.strip().str.lower().str.replace(" ", "_")
print(Data.columns)

Index(['year', 'make', 'model', 'trim', 'body', 'transmission', 'vin', 'state',
       'condition', 'odometer', 'color', 'interior', 'seller', 'mmr',
       'sellingprice', 'saledate'],
      dtype='object')

In [54]:
# Convert income column to float after removing $ and commas
if 'mmr' in Data.columns:
    Data['mmr'] = Data['mmr'].replace(r'[\$,]', '', regex=True).astype(float)
    print(Data['mmr'])

0         20500.0
1         20800.0
2         31900.0
3         27500.0
4         66000.0
           ...
558831    20300.0
558833    30200.0
558834    29800.0
558835    15100.0
558836    29600.0
Name: mmr, Length: 472325, dtype: float64

In [53]:
# Step 8: Standardize text columns
if 'model' in Data.columns:
    Data['model'] = Data['model'].str.lower().str.strip()
    print( Data['model'])

0                     sorento
1                     sorento
2                    3 series
3                         s60
4         6 series gran coupe
                 ...
558831               5 series
558833                   2500
558834                     x5
558835                 altima
558836                  f-150
Name: model, Length: 472325, dtype: object

In [55]:
# Step 9: Final check of dataset
print("\nCleaned Dataset Preview:\n", Data.head())
print("\nUpdated Data Types:\n", Data.dtypes)

Cleaned Dataset Preview:
    year   make                model        trim   body transmission  \
0  2015    Kia              sorento          LX    SUV    automatic
1  2015    Kia              sorento          LX    SUV    automatic
2  2014    BMW             3 series  328i SULEV  Sedan    automatic
3  2015  Volvo                  s60          T5  Sedan    automatic
4  2014    BMW  6 series gran coupe        650i  Sedan    automatic

                 vin state  condition  odometer  color interior  \
0  5xyktca69fg566472    ca        5.0   16639.0  white    black
1  5xyktca69fg561319    ca        5.0    9393.0  white    beige
2  wba3c1c51ek116351    ca       45.0    1331.0   gray    black
3  yv1612tb4f1310987    ca       41.0   14282.0  white    black
4  wba6b2c57ed129731    ca       43.0    2641.0   gray    black

                                   seller      mmr  sellingprice  \
0                 kia motors america  inc  20500.0       21500.0
1                 kia motors america  inc  20800.0       21500.0
2  financial services remarketing (lease)  31900.0       30000.0
3                 volvo na rep/world omni  27500.0       27750.0
4  financial services remarketing (lease)  66000.0       67000.0

                                  saledate
0  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2  Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3  Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4  Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

Updated Data Types:
 year              int64
make             object
model            object
trim             object
body             object
transmission     object
vin              object
state            object
condition       float64
odometer        float64
color            object
interior         object
seller           object
mmr             float64
sellingprice    float64
saledate         object
dtype: object

In [57]:
# Step 10: Save the cleaned dataset
Data.to_csv("cleaned_dataset.csv", index=False)
print("\nCleaned dataset saved as 'cleaned_dataset.csv'")

Cleaned dataset saved as 'cleaned_dataset.csv'